services:
  - type: web
    name: vibes-fqic
    env: node
    plan: free
    buildCommand: "pip install yt-dlp && npm install"
    startCommand: "node backend/server.js"
    healthCheckPath: /
    preDeploy:
      command: "apt-get update && apt-get install -y ffmpeg"